name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose up -d
      - name: Test
        run: docker-compose run web coverage run -m pytest
      - name: Coverage Report
        run: docker-compose run web coverage report
